### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Sadin**
Didn't have this module installed, this is why the thisweekinfedora.py would not run correctly.

### CODE REVIEW

**Comment by pypingou** [comment]
This is part of the standard library, it should be there as soon as you install python. Which version of python do you run?

**Comment by Sadin** [comment]
I was using 2.7.9 I tried on both my Fedora 21 and Fedora 22 installations, as well as OSX. thisweekinfedora.py would not run for me until I got it using pip.

**Comment by Sadin** [comment]
I was under the impression it was standard as well so I overlooked it but grabbing it via pip fixed my issue running the script, so I don't know what else to say. :/

**Comment by pypingou** [comment]
Looking at the description from https://pypi.python.org/pypi/DateTime isn't encouraging.

Could it be a bug on Nikola itself?

**Comment by Sadin** [comment]
The Traceback.
```shell
Traceback (most recent call last):ild.state.change - page: 76/122
  File "twif.py", line 375, in <module>
    process_week()
  File "twif.py", line 343, in process_week
    datetime_to, datetime_from)
  File "twif.py", line 123, in get_fedora_contributors
    datetime_from, datetime_to, TOPICS[topic], full=True)
  File "twif.py", line 93, in query_datagrepper
    topic, cnt, json_out['pages'])
KeyError: 'pages'
```

When I posted it a while ago as a gist in IRC we thought it might be a nikola bug then too, I took a shot in the dark and installed that DateTime module. Everything runs smoothly now and ive been able to actually have content to populate my testing copy with to work on the design!

**Pull request closed without merging**
